# Services: se definen los servicios o contenedores que tendrá el proyecto.
services:
  db:
    image: postgres:16
    #Nombre fijo del contenedor de la BD.
    container_name: web_segura_bd 
    #Hace que el contenedor se reinicie automáticamente si se cae.
    restart: unless-stopped 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: web_seguro
    ports:
      - "5432:5432"
    volumes:
        #Guarda los datos aunque el contenedor se apague o se borre.
      - postgres_data:/var/lib/postgresql/data 
        #Le indica a docker que ejecute automáticamente el "schema.sql"
      - ./backend/src/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    # Docker construye el backend usando el "DockerFile"
    build: ./backend
    # Nombre fijo del contenedor de la BD.
    container_name: web_segura_backend
    # Hace que el contenedor se reinicie automáticamente si se cae.
    restart: unless-stopped
    # Expone el API
    ports:
      - "3000:3000"
    # Conecta el backend con Postgres
    env_file:
      - ./backend/.env
    # El backend depende de la BD
    depends_on:
      db:
        condition: service_healthy

  frontend:
    # Docker construye el frontend usando el "DockerFile"
    build: ./frontend
    # Nombre del contenedor del frontend
    container_name: web_segura_frontend
    # Reinicio automático
    restart: unless-stopped
    # Acceso al sistema
    ports:
      - "5173:5173"
    # Acceso a las variables 
    env_file:
      - ./frontend/.env
    # El frontend depende del backend
    depends_on:
      - backend

volumes:
  # Define que sea una almacenamiento persistente. Hace que no se borre la BD. 
  postgres_data: 
